import type { MetadataRoute } from 'next';

const isStaging = process.env.NEXT_PUBLIC_ENVIRONMENT === 'staging';

const AI_BOTS = [
  'AddSearchBot',
  'AI2Bot',
  'AI2Bot-DeepResearchEval',
  'Ai2Bot-Dolma',
  'aiHitBot',
  'Amazonbot',
  'AmazonBuyForMe',
  'Andibot',
  'anthropic-ai',
  'ApifyBot',
  'ApifyWebsiteContentCrawler',
  'Applebot-Extended',
  'Awario',
  'bedrockbot',
  'bigsur.ai',
  'Brightbot 1.0',
  'BuddyBot',
  'Bytespider',
  'CCBot',
  'Channel3Bot',
  'ChatGLM-Spider',
  'ChatGPT-User',
  'Claude-Web',
  'ClaudeBot',
  'Cloudflare-AutoRAG',
  'CloudVertexBot',
  'cohere-training-data-crawler',
  'Cotoyogi',
  'Crawl4AI',
  'Crawlspace',
  'Datenbank Crawler',
  'DeepSeekBot',
  'Diffbot',
  'Echobot Bot',
  'EchoboxBot',
  'ExaBot',
  'FacebookBot',
  'facebookexternalhit',
  'Factset_spyderbot',
  'FirecrawlAgent',
  'FriendlyCrawler',
  'Gemini-Deep-Research',
  'Google-CloudVertexBot',
  'Google-Extended',
  'Google-Firebase',
  'Google-NotebookLM',
  'GoogleOther',
  'GoogleOther-Image',
  'GoogleOther-Video',
  'GPTBot',
  'iAskBot',
  'iaskspider',
  'iaskspider/2.0',
  'ICC-Crawler',
  'ImagesiftBot',
  'imageSpider',
  'img2dataset',
  'ISSCyberRiskCrawler',
  'Kangaroo Bot',
  'KunatoCrawler',
  'laion-huggingface-processor',
  'LAIONDownloader',
  'LCC',
  'Linguee Bot',
  'LinkupBot',
  'Manus-User',
  'meta-externalagent',
  'Meta-ExternalAgent',
  'meta-externalfetcher',
  'Meta-ExternalFetcher',
  'meta-webindexer',
  'MyCentralAIScraperBot',
  'netEstate Imprint Crawler',
  'NotebookLM',
  'NovaAct',
  'omgili',
  'omgilibot',
  'OpenAI',
  'PanguBot',
  'Panscient',
  'panscient.com',
  'PerplexityBot',
  'Poggio-Citations',
  'Poseidon Research Crawler',
  'QualifiedBot',
  'QuillBot',
  'quillbot.com',
  'SBIntuitionsBot',
  'Scrapy',
  'SemrushBot-OCOB',
  'SemrushBot-SWA',
  'Sidetrade indexer bot',
  'Spider',
  'TavilyBot',
  'TerraCotta',
  'Thinkbot',
  'TikTokSpider',
  'Timpibot',
  'TwinAgent',
  'VelenPublicWebCrawler',
  'WARDBot',
  'Webzio-Extended',
  'webzio-extended',
  'wpbot',
  'WRTNBot',
  'YandexAdditional',
  'YandexAdditionalBot',
  'YouBot',
];

export default function robots(): MetadataRoute.Robots {
  if (isStaging) {
    return {
      rules: { userAgent: '*', disallow: '/' },
    };
  }

  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
      },
      {
        userAgent: AI_BOTS,
        disallow: '/',
      },
    ],
    sitemap: 'https://hammercreative.com/sitemap.xml',
  };
}
