/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type VideoItem = {
  _type: 'videoItem';
  title?: string;
  video?: MuxVideo;
  poster?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
};

export type TextBlock = {
  _type: 'textBlock';
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'blockquote';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type ImageItem = {
  _type: 'imageItem';
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  caption?: string;
};

export type Seo = {
  _type: 'seo';
  title?: string;
  description?: string;
  keywords?: Array<string>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type VideoModule = {
  _type: 'videoModule';
  videos?: Array<
    {
      _key: string;
    } & VideoItem
  >;
  backgroundColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
};

export type DeliverablesModule = {
  _type: 'deliverablesModule';
  deliverables?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'deliverable';
  }>;
};

export type ServicesModule = {
  _type: 'servicesModule';
  services?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'service';
  }>;
};

export type ServicesPageHeroModule = {
  _type: 'servicesPageHeroModule';
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'blockquote';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  backgroundColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
  textColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
};

export type ServicesPageCardModule = {
  _type: 'servicesPageCardModule';
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'blockquote';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  services?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'service';
  }>;
  backgroundColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
  textColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
};

export type SingleImageModule = {
  _type: 'singleImageModule';
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  backgroundColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
};

export type TextImageModule = {
  _type: 'textImageModule';
  layout?: 'textRight' | 'textLeft';
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'blockquote';
    listItem?: never;
    markDefs?: Array<
      | {
          href?: string;
          _type: 'link';
          _key: string;
        }
      | {
          name?:
            | 'nightshade'
            | 'sandstorm'
            | 'aircutter'
            | 'hyperbeam'
            | 'hydroblast'
            | 'vinewhip';
          _type: 'color';
          _key: string;
        }
    >;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  backgroundColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
  textColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
};

export type TextModule = {
  _type: 'textModule';
  layout?: 'headlineLeft' | 'headlineMiddle' | 'homePage';
  client?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'client';
  };
  tag?: string;
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'blockquote';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  backgroundColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
  textColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
};

export type CaseStudyCardModule = {
  _type: 'caseStudyCardModule';
  caseStudies?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'caseStudy';
  }>;
};

export type CarouselModule = {
  _type: 'carouselModule';
  images?: Array<
    {
      _key: string;
    } & ImageItem
  >;
  backgroundColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
};

export type ImpactModule = {
  _type: 'impactModule';
  layout?: 'threeText' | 'twoTextOneImage' | 'oneTextOneImage';
  textBlock1?: TextBlock;
  textBlock2?: TextBlock;
  textBlock3?: TextBlock;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  backgroundColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
  textColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
};

export type HeroModule = {
  _type: 'heroModule';
  title?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'blockquote';
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  teaserImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  services?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'service';
  }>;
  deliverables?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'deliverable';
  }>;
  backgroundColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
  textColor?: {
    enabled?: boolean;
    name?:
      | 'nightshade'
      | 'sandstorm'
      | 'aircutter'
      | 'hyperbeam'
      | 'hydroblast'
      | 'vinewhip';
  };
};

export type ServicesPage = {
  _id: string;
  _type: 'servicesPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  modules?: Array<
    | ({
        _key: string;
      } & ServicesPageHeroModule)
    | ({
        _key: string;
      } & ServicesPageCardModule)
  >;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  modules?: Array<
    | ({
        _key: string;
      } & CaseStudyCardModule)
    | ({
        _key: string;
      } & TextModule)
  >;
};

export type Deliverable = {
  _id: string;
  _type: 'deliverable';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
};

export type CaseStudy = {
  _id: string;
  _type: 'caseStudy';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  clients?: Array<{
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: 'client';
  }>;
  modules?: Array<
    | ({
        _key: string;
      } & HeroModule)
    | ({
        _key: string;
      } & TextImageModule)
    | ({
        _key: string;
      } & VideoModule)
    | ({
        _key: string;
      } & TextModule)
    | ({
        _key: string;
      } & SingleImageModule)
    | ({
        _key: string;
      } & CarouselModule)
    | ({
        _key: string;
      } & ImpactModule)
  >;
};

export type MuxVideo = {
  _type: 'mux.video';
  asset?: {
    _ref: string;
    _type: 'reference';
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: 'mux.videoAsset';
  };
};

export type Client = {
  _id: string;
  _type: 'client';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  website?: string;
};

export type MuxVideoAsset = {
  _id: string;
  _type: 'mux.videoAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  status?: string;
  assetId?: string;
  playbackId?: string;
  filename?: string;
  thumbTime?: number;
  data?: MuxAssetData;
};

export type MuxAssetData = {
  _type: 'mux.assetData';
  resolution_tier?: string;
  upload_id?: string;
  created_at?: string;
  id?: string;
  status?: string;
  max_stored_resolution?: string;
  passthrough?: string;
  encoding_tier?: string;
  video_quality?: string;
  master_access?: string;
  aspect_ratio?: string;
  duration?: number;
  max_stored_frame_rate?: number;
  mp4_support?: string;
  max_resolution_tier?: string;
  tracks?: Array<
    {
      _key: string;
    } & MuxTrack
  >;
  playback_ids?: Array<
    {
      _key: string;
    } & MuxPlaybackId
  >;
  static_renditions?: MuxStaticRenditions;
};

export type MuxStaticRenditions = {
  _type: 'mux.staticRenditions';
  status?: string;
  files?: Array<
    {
      _key: string;
    } & MuxStaticRenditionFile
  >;
};

export type MuxStaticRenditionFile = {
  _type: 'mux.staticRenditionFile';
  name?: string;
  ext?: string;
  height?: number;
  width?: number;
  bitrate?: number;
  filesize?: string;
  type?: string;
  status?: string;
  resolution_tier?: string;
  resolution?: string;
  id?: string;
  passthrough?: string;
};

export type MuxPlaybackId = {
  _type: 'mux.playbackId';
  id?: string;
  policy?: string;
};

export type MuxTrack = {
  _type: 'mux.track';
  id?: string;
  type?: string;
  max_width?: number;
  max_frame_rate?: number;
  duration?: number;
  max_height?: number;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | VideoItem
  | TextBlock
  | ImageItem
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | VideoModule
  | DeliverablesModule
  | ServicesModule
  | ServicesPageHeroModule
  | ServicesPageCardModule
  | SingleImageModule
  | TextImageModule
  | TextModule
  | CaseStudyCardModule
  | CarouselModule
  | ImpactModule
  | HeroModule
  | ServicesPage
  | Slug
  | Service
  | HomePage
  | Deliverable
  | CaseStudy
  | MuxVideo
  | Client
  | MuxVideoAsset
  | MuxAssetData
  | MuxStaticRenditions
  | MuxStaticRenditionFile
  | MuxPlaybackId
  | MuxTrack
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
