#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
MSG_FILE="$1"
MSG_CONTENT=$(cat "$MSG_FILE")

# Insert branch *after* type:
# chore: [main] testing husky
UPDATED_MSG=$(echo "$MSG_CONTENT" | sed -E "s/^([a-z]+)(\(.+\))?: /\\1\\2: [${BRANCH_NAME}] /")

echo "$UPDATED_MSG" > "$MSG_FILE"
