#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME="$(git rev-parse --abbrev-ref HEAD | tr '/' '-')"
MSG_FILE="$1"

# only modify if line matches a conventional commit type
FIRST_LINE="$(head -n1 "$MSG_FILE")"
if echo "$FIRST_LINE" | grep -Eq '^[a-z]+(\([^)]+\))?: '; then
  UPDATED_MSG="$(echo "$FIRST_LINE" | sed -E "s/^([a-z]+)(\([^)]+\))?: /\1\2: [${BRANCH_NAME}] /")"
  tail -n +2 "$MSG_FILE" | { echo "$UPDATED_MSG"; cat; } > "$MSG_FILE.tmp"
  mv "$MSG_FILE.tmp" "$MSG_FILE"
fi
